import { useEffect, useState } from 'react';
import { supabase } from '@/integrations/supabase/client';
import { Occurrence, OccurrenceStatus, PriorityLevel, OccurrenceType } from '@/types/sigor';
import { useToast } from '@/hooks/use-toast';

export function useOccurrences(organizationId?: string) {
  const [occurrences, setOccurrences] = useState<Occurrence[]>([]);
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  const fetchOccurrences = async () => {
    try {
      let query = supabase
        .from('occurrences')
        .select('*, organization:organizations(*)')
        .order('created_at', { ascending: false });

      if (organizationId) {
        query = query.eq('organization_id', organizationId);
      }

      const { data, error } = await query;

      if (error) throw error;
      setOccurrences(data as Occurrence[]);
    } catch (error) {
      console.error('Error fetching occurrences:', error);
      toast({
        title: 'Erro ao carregar ocorrências',
        description: 'Tente novamente mais tarde.',
        variant: 'destructive',
      });
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchOccurrences();

    // Subscribe to realtime updates
    const channel = supabase
      .channel('occurrences-changes')
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'occurrences',
        },
        (payload) => {
          if (payload.eventType === 'INSERT') {
            const newOccurrence = payload.new as Occurrence;
            setOccurrences(prev => [newOccurrence, ...prev]);
            
            // Play alert sound for new occurrences
            if (newOccurrence.priority === 'critical' || newOccurrence.priority === 'high') {
              playAlertSound();
            }
          } else if (payload.eventType === 'UPDATE') {
            setOccurrences(prev =>
              prev.map(o => o.id === payload.new.id ? payload.new as Occurrence : o)
            );
          } else if (payload.eventType === 'DELETE') {
            setOccurrences(prev => prev.filter(o => o.id !== payload.old.id));
          }
        }
      )
      .subscribe();

    return () => {
      supabase.removeChannel(channel);
    };
  }, [organizationId]);

  const createOccurrence = async (data: {
    organization_id: string;
    type: OccurrenceType;
    priority: PriorityLevel;
    title: string;
    description?: string;
    caller_name?: string;
    caller_phone?: string;
    location_address?: string;
    location_reference?: string;
    latitude?: number | null;
    longitude?: number | null;
  }) => {
    const { data: user } = await supabase.auth.getUser();
    if (!user.user) throw new Error('Not authenticated');

    const { data: occurrence, error } = await supabase
      .from('occurrences')
      .insert({
        ...data,
        code: 'TEMP', // Will be generated by trigger
        created_by: user.user.id,
      })
      .select()
      .single();

    if (error) throw error;
    return occurrence;
  };

  const updateOccurrenceStatus = async (
    occurrenceId: string, 
    status: OccurrenceStatus,
    notes?: string
  ) => {
    const { data: user } = await supabase.auth.getUser();
    if (!user.user) throw new Error('Not authenticated');

    const occurrence = occurrences.find(o => o.id === occurrenceId);
    
    // Update occurrence
    const { error } = await supabase
      .from('occurrences')
      .update({ 
        status,
        ...(status === 'completed' || status === 'cancelled' ? {
          closed_by: user.user.id,
          closed_at: new Date().toISOString(),
        } : {})
      })
      .eq('id', occurrenceId);

    if (error) throw error;

    // Add to history
    await supabase.from('occurrence_history').insert({
      occurrence_id: occurrenceId,
      previous_status: occurrence?.status,
      new_status: status,
      changed_by: user.user.id,
      notes,
    });
  };

  return {
    occurrences,
    loading,
    refetch: fetchOccurrences,
    createOccurrence,
    updateOccurrenceStatus,
  };
}

function playAlertSound() {
  const audio = new Audio('/alert.mp3');
  audio.play().catch(() => {
    // Ignore audio play errors (autoplay might be blocked)
    console.log('Audio autoplay blocked');
  });
}
